### ISSUE TITLE
classes table doesn't take the full width of the article

### ISSUE THREAD

**Issue by 12rambau** [jbms/sphinx-immaterial#288] opened 2023-09-07 13:16 UTC
I have some small classes in my project with very short descriptions. When using immaterial along with autoapi, the classes table get reduce making it inconsistent with the Functions one: 

<img width="406" alt="image" src="https://github.com/jbms/sphinx-immaterial/assets/12596392/5098a5df-1363-4201-bcfb-407b78e745a4">
 
Is it wanted ?

**Comment by 2bndy5** [comment] 2023-09-08 01:05
If you mean the tale width being adaptive to its contents, then yes, that is expected.

**Comment by 12rambau** [comment] 2023-09-08 07:41
ok I'll find the appropriate css selector to change it in custom.css and post it here before closing the issue.

**Comment by 2bndy5** [comment] 2023-09-08 07:51
Tried doing this already... Found that removing `box-size: inherit` changes the width of the entire table, but the rows/headers need additional tweaking.

Please also remember, the [Material design rules](https://m2.material.io/components/data-tables) are fundamental to this theme (and its upstream source in mkdocs).

**Comment by 12rambau** [comment] 2023-09-08 08:35
I added the follwing to my  custom.css and it works as expected: 

```css 

/* make autosummary tables use all the width available */
table.autosummary {
  width: 100% !important;
}

table.autosummary tr:not(:last-child) {
  white-space: nowrap !important;
}

table.autosummary td:last-child {
  width: 99% !important;
}
```

Of course as it's my custom one I've been very lazy on the selector description and used !important instead. 

<img width="960" alt="image" src="https://github.com/jbms/sphinx-immaterial/assets/12596392/99bf9ac8-2df4-41e2-bb99-7fee7e19c790">


If it's not a wanted feature feel free to close my issue, if not I can try to find the exact selector in your scss.

**Comment by 2bndy5** [comment] 2023-09-08 09:27
Glad to see you got it working. I wouldn't call this a wanted feature. Most of our CSS (& JS) is from upstream mkdocs-material, and we try to keep the changes minimal to make merging in updates from upstream easier.

Since your workaround is more specific to autosummary (something autoapi probably uses underneath), I think what you were expecting is how auto-summary works for other themes that actually use Sphinx basic theme's CSS (this theme is an exception to that assumption).

If you think it necessary that the autosummary tables should be absolutely wide, then I think there may be a place for that after:
https://github.com/jbms/sphinx-immaterial/blob/22fd15f3d71c0f08a33713b4f25221406ea1a305/src/assets/stylesheets/main/_api.scss#L273-L283

BTW: we're the reason that autosummary tables have their own CSS class 😉. So the above SCSS rule could be updated now that they've released that change.

**Comment by 12rambau** [comment] 2023-09-08 23:59
I was doubting so I check the template I'm maintaining (pydata-sphinx-theme) and yes, the autosummary tables are taking the full width of the page (https://pygadm.readthedocs.io/en/stable/api/pygadm/index.html#package-contents). 
I'm no expert on the mkdocs ecosystem but I never saw tables like the autosummary ones so my guess is that such a change should be harmless as it's not covered by materialDoc itself.

**Comment by 2bndy5** [comment] 2023-09-09 00:05
Like I said, there's room for autosummary-specific changes in [src/assets/stylesheets/main/_api.scss](https://github.com/jbms/sphinx-immaterial/blob/22fd15f3d71c0f08a33713b4f25221406ea1a305/src/assets/stylesheets/main/_api.scss#L273-L283).

**Comment by 2bndy5** [comment] 2024-07-05 03:17
I'm closing this as it isn't a popular request.

Furthermore, using `!important` in our SCSS would trigger linter errors. The fact that `!important` is used in the proposed solution suggests that there might be a regression or other CSS conflict (or maybe the selectors just need to be more specific somehow).

**Closed by 2bndy5** 2024-07-05 03:17 UTC
